# AVCGA CrewHub - Docker Compose Configuration
# Complete system with proper environment handling

services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${DB_NAME:-avcga_crew_hub}
      POSTGRES_USER: ${DB_USER:-avcga_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Archie1977}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/sql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-avcga_user} -d ${DB_NAME:-avcga_crew_hub}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API Service (Node.js/Express)
  backend:
    build:
      context: ./backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  # Frontend Member Portal (React.js)
  member-web:
    build:
      context: ./member-web
    restart: always
    ports:
      - "8080:80"

  # Frontend Admin Portal (React.js)
  web-admin:
    build:
      context: ./web-admin
    restart: always
    ports:
      - "8081:80"

volumes:
  db_data:
